version: "3.8"
    
services:
  wpdb:
    image: mysql:5.7
    container_name: wpdb_$USER
    volumes:
      - wpdbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - wpdb
    image: wordpress:latest
    container_name: wordpress_$USER
    volumes:
      - wpdata:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  wpdbdata:
    name: wpdbdata_$USER
  wpdata:
    name: wpdata_$USER
